language: go

go:
  - 1.6
  - 1.7
  - tip

before_install:
  - go get github.com/tools/godep

install:
  - godep restore

script:
  - go test -v ./...

notifications:
  email:
    - marek.mikuliszyn@gmail.com
